baseURL: 'https://wowios.com'
languageCode: en-us 
title: Zanxinz
theme: "PaperMod"
publishdir: "./docs/"

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: categories
      name: ğŸ“–ç±»åˆ«
      url: /categories/
      weight: 10
    - identifier: tags
      name: ğŸ·ï¸æ ‡ç­¾
      url: /tags/
      weight: 20
    - identifier: archive
      name: ğŸ“¦å½’æ¡£
      url: /archive/
      weight: 5
    - identifier: search
      name: ğŸ”æœç´¢
      url: /search/
      weight: 30
    - identifier: about
      name: ğŸ§‘â€ğŸ’»æˆ‘
      url: /about/
      weight: 40
      

params:
  # é¡µé¢åº•éƒ¨åˆ†äº«æ 
  ShowShareButtons: true
  ShareButtons: ["telegram", "reddit", "twitter"]
  defaultTheme: auto
  # ä¸»é¡µçš„æ¨¡å¼
  homeInfoParams:
    enabled: true
    Title: Welcome ğŸ‘
    Content:  "Here is Zanxinz's blog"
  # ç¤¾äº¤è”ç³»æ–¹å¼
  socialIcons: 
    - name: "twitter"
      url: "https://twitter.com/zanxinz"
    - name: "github"
      url: "https://github.com/ZanxinZ"
    - name: "email"
      url: "post/info/contact/mail"
  # å›åˆ°é¡¶éƒ¨
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  env: production
  cover:
    responsiveImages: fasle
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

assets:
  disableHLJS: true
  favicon: "/img/cloud32.png"
  favicon16x16: "/img/cloud16.png"
  favicon32x32: "/img/cloud32.png"
  apple_touch_icon: "/img/cloud32.png"
  safari_pinned_tab: "/img/cloud32.png"

outputs:
  home:
    - HTML
    - RSS
    - JSON

ignoreLogs : ['warning-goldmark-raw-html']
