baseURL: 'https://1-1.link'
languageCode: en-us 
title: CodePaper
theme: "PaperMod"
publishdir: "./docs/"

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: categories
      name: ç±»åˆ«
      url: /categories/
      weight: 10
    - identifier: tags
      name: æ ‡ç­¾
      url: /tags/
      weight: 20
    - identifier: archive
      name: æ¡£æ¡ˆ
      url: /archive/
      weight: 5
    - identifier: search
      name: æœç´¢
      url: /search/
      weight: 30

params:
  # é¡µé¢åº•éƒ¨åˆ†äº«æ 
  ShowShareButtons: true
  ShareButtons: ["telegram", "reddit", "twitter"]
  defaultTheme: auto
  # ä¸»é¡µçš„æ¨¡å¼
  homeInfoParams:
    enabled: true
    Title: ZanxinzğŸ‘‹
    Content:  ""
  # ç¤¾äº¤è”ç³»æ–¹å¼
  socialIcons: 
    - name: "twitter"
      url: "https://twitter.com/zanxinz"
    - name: "github"
      url: "https://github.com/ZanxinZ"
    - name: "email"
      url: "post/info/contact/mail"
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  env: production
 
outputs:
  home:
    - HTML
    - RSS
    - JSON
